otterize/otterize-cli

src/pkg/cloudclient/environments/client.go, src/pkg/cloudclient/environments/generated.go, src/pkg/cloudclient/environments/genqlient.graphql, src/pkg/cloudclient/integrations/client.go, src/pkg/cloudclient/integrations/generated.go, src/pkg/cloudclient/integrations/genqlient.graphql, src/pkg/cloudclient/invites/generated.go, src/pkg/cloudclient/organizations/generated.go, src/pkg/cloudclient/users/generated.go
Bump cloud graphQL revision to support SOFA routes customizations.
=> Bump graphql version (sofa routes customization adaptations)

src/CODEOWNERS, src/pkg/cloudclient/environments/client.go, src/pkg/cloudclient/environments/generated.go, src/pkg/cloudclient/environments/genqlient.graphql, src/pkg/cloudclient/integrations/client.go, src/pkg/cloudclient/integrations/generated.go, src/pkg/cloudclient/integrations/genqlient.graphql, src/pkg/cloudclient/organizations/client.go, src/pkg/cloudclient/organizations/generated.go, src/pkg/cloudclient/organizations/genqlient.graphql
https://www.notion.so/otterize/Flatten-REST-update-operations-body-to-match-standards-e-g-eliminate-EnvironmentUpdate-object-and--756f0473f7ee466791b5fbf52e830a15
=> Flatten organizations, integrations & environments update body

src/cmd/login/login.go, src/cmd/users/create/config.go, src/cmd/users/create/create-user.go, src/pkg/cloudclient/graphql/users/client.go, src/pkg/cloudclient/graphql/users/generated.go, src/pkg/cloudclient/graphql/users/genqlient.graphql, src/pkg/cloudclient/restapi/cloudapi/api.gen.go, src/pkg/output/formatters.go
Rename User type Auth0 fields to AuthProvider fields (abstracts away the particular auth provider).
=> Rename Auth0UserID & Info to AuthProviderUserID & Info

.github/workflows/golangci-lint.yml, src/pkg/output/format.go, src/pkg/portforwarder/portforwarder.go
Add golangci-lint workflow + fix linter issues
=> Add golangci-lint workflow + fix linter issues

src/cmd/environments/delete/delete-env.go, src/pkg/cloudclient/restapi/cloudapi/api.gen.go, src/pkg/output/formatters.go
Bump CLI API version to latest & fix what's broken.
=> Bump CLI version + fixes

src/pkg/cloudclient/graphql/client.go, src/pkg/cloudclient/restapi/client.go
=> Set API version to v1beta

src/cmd/version/apiversion.go
Add upgrade instructions link to api-version comment
=> Add upgrade instructions link to api-version comment

src/cmd/clusters/clusters.go, src/cmd/clusters/create/config.go, src/cmd/clusters/create/create-cluster.go, src/cmd/clusters/delete/delete-cluster.go, src/cmd/clusters/get/get-cluster.go, src/cmd/clusters/list/config.go, src/cmd/clusters/list/list-clusters.go, src/cmd/clusters/update/config.go, src/cmd/clusters/update/update-cluster.go, src/cmd/environments/create/create-env.go, src/cmd/integrations/create/config.go, src/cmd/integrations/create/create-kubernetes-integration.go, src/cmd/namespaces/get/get-namespace.go, src/cmd/namespaces/list/config.go, src/cmd/namespaces/list/list-namespaces.go, src/cmd/namespaces/namespaces.go, src/cmd/namespaces/update/config.go, src/cmd/namespaces/update/update-namespace.go, src/cmd/root.go, src/pkg/cloudclient/restapi/cloudapi/api.gen.go, src/pkg/cloudclient/restapi/cloudapi/openapi.json, src/pkg/output/formatters.go
* Implement CLI commands for clusters:
** list
** get 
** create
** update
** delete
* Implement CLI commands for namespaces:
** get
** list
** update
* Make create env command `name` argument required
* Add `cluster-id`aregument to create k8s integration command
=> Implement clusters & namespaces CLI commands

src/pkg/cloudclient/restapi/client.go
Fix breakage in successful CLI commands following https://github.com/otterize/otterize-cli/pull/48
=> Fix breaking successful commands

src/pkg/cloudclient/restapi/cloudapi/api.gen.go, src/pkg/cloudclient/restapi/cloudapi/openapi.json
changed REST path for accept invite from /invite/:id/accept to /invite/:id
https://www.notion.so/otterize/Invites-API-improvements-3418bfccddb243fc8c1dfd8f717d6e7b
=> Changed accept invite REST path

src/cmd/services/list/list-services.go
This PR fix services output to table format
=> Print services list as table

src/cmd/intents/list/list-intents.go, src/pkg/output/format_intents.go
This PR fix intents output to table format
=> Print intents as table

src/pkg/cloudclient/restapi/cloudapi/api.gen.go, src/pkg/cloudclient/restapi/cloudapi/openapi.json, src/pkg/config/config.go, src/pkg/output/format.go, src/pkg/output/formatters.go
* Review different object columns and format them according to specs
* Support yaml output
=> Format object columns according to API specs

src/cmd/environments/list/list-envs.go, src/cmd/environments/update/remove-label.go, src/cmd/organizations/removeuser/remove-user-from-organization.go, src/pkg/cloudclient/restapi/cloudapi/api.gen.go, src/pkg/cloudclient/restapi/cloudapi/openapi.json
* Bump openapi specs version
* Fix remove label & remove user issue - passed via query params instead of body
* hide label param from `environments list` command
=> Bump API version - fix remove label & remove user issue, hide label param from list-envs

src/cmd/invites/invites.go, src/pkg/cloudclient/restapi/cloudapi/api.gen.go, src/pkg/cloudclient/restapi/cloudapi/openapi.json
add invites alias as invite singular + update api version
=> add invites alias as invite singular + update api version

src/pkg/output/formatters.go
Hide image URL from users & orgs list.
=> Hide image URL from users & orgs tables

src/cmd/invites/create/create-invite.go, src/cmd/root.go, src/cmd/version/apiversion.go, src/pkg/cloudclient/login/userlogin/userlogin.go, src/pkg/cloudclient/restapi/client.go, src/pkg/cloudclient/restapi/cloudapi/api.gen.go, src/pkg/cloudclient/restapi/cloudapi/openapi.json, src/pkg/cloudclient/restapi/generate.go, src/pkg/cloudclient/restapi/version.go
* Bump REST API version to support input validation
* Move API docs & openapi.json to /api/rest/v1beta
=> Bump API version (input validation)

go.sum, src/cmd/networkmapper/export/mapper-export.go, src/mappergraphql/schema.graphql, src/pkg/mapperclient/client.go, src/pkg/mapperclient/generated.go, src/pkg/mapperclient/genqlient.graphql, src/pkg/utils/prints/utils.go
=> Added mapper export with distinct by label (experimental)

src/cmd/namespaces/associatetoenvironment/associate-to-environment.go, src/cmd/namespaces/namespaces.go, src/cmd/namespaces/update/update-namespace.go, src/pkg/cloudclient/restapi/cloudapi/api.gen.go, src/pkg/cloudclient/restapi/cloudapi/openapi.json
Update `namespaces update` command with new API
=> Rename update namespace mutation

go.mod, go.sum, src/cmd/accessgraph/accessgraph.go, src/cmd/accessgraph/get/get-accessgraph.go, src/cmd/root.go, src/pkg/output/formatters.go
Allow the user to get access graph data from CLI
=> Get access graph from cli

.goreleaser.yaml
=> Disable upx on mac amd64

src/cmd/root.go, src/pkg/config/config.go, src/pkg/output/format.go, src/pkg/output/formatters.go
- Change tabulate output to no borders format
- Capitalize all output column headers
- Add a global opt-in flag to suppress output column header (same as `--no-headers` flag in kubectl)
- For all resources, if the output table is empty, we display “No resources found” message
=> Update table print formatting

src/pkg/cloudclient/graphql/schema.graphql, src/pkg/cloudclient/restapi/cloudapi/api.gen.go, src/pkg/cloudclient/restapi/cloudapi/openapi.json, src/pkg/cloudclient/restapi/generate.go
Load latest API version & generate CLI code.
=> Bump CLI API version

src/cmd/environments/list/list-envs.go, src/pkg/cloudclient/restapi/cloudapi/api.gen.go, src/pkg/cloudclient/restapi/cloudapi/openapi.json
https://www.notion.so/otterize/CLI-doc-for-environments-list-has-some-issues-66d78f9897474b3a836da6095d98fde7?pvs=4
=> Add labels filter to envs query, replace stringToString with labels

src/cmd/networkmapper/visualize/mapper-visualize.go
This PR improves scaling for visualization - before, the proportions were sometimes extremely small or large.
=> Improve visualize scaling

src/cmd/networkmapper/visualize/mapper-visualize.go
Use PNG as it's better for simple graphics vs JPG
=> Change visualizer default format

src/pkg/kafkamapper/mapper.go
Fix merge intent topics not reflecting changes at caller
=> Fix merge intent topics not reflecting changes at caller

src/pkg/intentsoutput/intentsvisualizer/visualizer.go
Due to some CLI changes, namespaces were accidentally dropped from service names in network mapper visualized graphs. This PR contains a fix for that.
=> Fixing missing namespace in service names for visualize cmd

src/pkg/intentsoutput/transform.go
* Eliminate duplicate typed vs untyped intents reported in otterize mapper cli
* Sort returned intents for CLI consistency
=> Eliminate duplicate typed vs untyped intents reported in otterize mapper cli

src/cmd/networkmapper/export/mapper-export.go, src/cmd/networkmapper/list/mapper-list.go, src/cmd/networkmapper/mapper.go, src/cmd/networkmapper/shared/shared.go, src/pkg/cloudclient/graphql/schema.graphql, src/pkg/cloudclient/restapi/cloudapi/api.gen.go, src/pkg/cloudclient/restapi/cloudapi/openapi.json, src/pkg/intentsoutput/intentslister/lister.go, src/pkg/mapperclient/client.go, src/pkg/mapperclient/config.go, src/pkg/mapperclient/generated.go, src/pkg/mapperclient/genqlient.graphql, src/pkg/mapperclient/schema.graphql
* Added support for exclusion by (Otterize) service names
* Added support for exclusion by labels
=> Support excluding in mapper querying

.github/workflows/release-tag.yaml, .goreleaser.yaml
Changing destination bucket to GCS from S3
=> Changing destination bucket to GCS from S3

.github/workflows/release-tag.yaml
Fix update docs upon release bu using github.ref_name instead of github.ref/
=> Fix update docs upon release

src/cmd/networkmapper/export/mapper-export.go, src/cmd/networkmapper/shared/shared.go, src/pkg/cloudclient/graphql/schema.graphql, src/pkg/cloudclient/restapi/cloudapi/api.gen.go, src/pkg/cloudclient/restapi/cloudapi/openapi.json, src/pkg/mapperclient/client.go, src/pkg/mapperclient/generate.go, src/pkg/mapperclient/generated.go, src/pkg/mapperclient/genqlient.graphql, src/pkg/mapperclient/schema.graphql, src/pkg/output/formatters.go
Change server filter in mapper export command to the format: <server>.<namespace>
=> Filter export with the format <server>.<namespace>

.github/workflows/build-fork.yaml, .github/workflows/build.yaml
This PR fixes the build job, which could not run on forks due to reliance on secrets.
=> Fix build for forks

src/cmd/integrations/create/create-kubernetes-integration.go, src/cmd/integrations/update/update-kubernetes-integration.go, src/pkg/cloudclient/graphql/generated.go, src/pkg/cloudclient/graphql/schema.graphql, src/pkg/cloudclient/restapi/cloudapi/api.gen.go, src/pkg/cloudclient/restapi/cloudapi/openapi.json, src/pkg/mapperclient/generated.go, src/pkg/mapperclient/schema.graphql, src/pkg/telemetry/telemetrygql/generated.go, src/pkg/telemetry/telemetrygql/schema.graphql
This PR removes the clusters commands from the CLI and updates the integrations commands to support the latest changes in the cloud in which we removed the Clusters page and combined it into the Integrations page.
=> Combine the clusters and integrations commands

src/pkg/cloudclient/restapi/client.go, src/pkg/cloudclient/restapi/utils.go, src/pkg/config/persistent_config.go
Added resolving for organization ID from flags first and then config file - this fixes the bug where org id from flag was overwritten by the one in the config file.
=> Added resolving for organization ID from flags first and then config file

src/pkg/intentsoutput/intentsvisualizer/visualizer.go
Fix bug where the mapper could not perform visualize
=> Fix bug where  `otterize mapper` could not perform visualize

src/pkg/cli/flags.go
Update `otterize clientintents export` cli docs with new filter by name capability. 
https://github.com/otterize/otterize-cli/pull/168
=> Update `clientintents export` docs with new filter by name capability
