otterize/otterize-cli

- src/cmd/mapper/mapper-export.go
- src/pkg/intentsprinter/printer.go
This PR remove the default value of HTTP from intent type since it's no longer mandatory to have type for every intent, and by default intents should come without type
> Export intents by default without type

- src/cmd/environments/create/create-env.go
- src/cmd/environments/delete/delete-env.go
- src/cmd/environments/get/get-env.go
- src/cmd/environments/list/list-envs.go
- src/cmd/environments/update/add-labels.go
- src/cmd/environments/update/remove-labels.go
- src/cmd/environments/update/update-env.go
- src/cmd/integrations/create/create-integration.go
- src/cmd/integrations/delete/delete-integration.go
- src/cmd/integrations/get/get-integration.go
- src/cmd/integrations/list/list-integrations.go
- src/cmd/integrations/update/update-integration.go
- src/cmd/invites/accept/accept-invite.go
- src/cmd/invites/create/create-invite.go
- src/cmd/invites/delete/delete-invite.go
- src/cmd/invites/list/list-invites.go
- src/cmd/login/login.go
- src/cmd/organizations/create/create-organization.go
- src/cmd/organizations/get/get-organization.go
- src/cmd/organizations/list/list-organizations.go
- src/cmd/organizations/update/update-organization.go
- src/cmd/users/create/create-user.go
- src/cmd/users/delete/delete-user.go
- src/cmd/users/get/get-user.go
- src/cmd/users/list/list-users.go
- src/pkg/cloudclient/restapi/client.go
- src/pkg/cloudclient/restapi/cloudapi/api.gen.go
* Bump API version after replacing /objects/one endpoint with /object
* Use oapi-codegen built-in security provider, simplify cloudclient init and struct
> bump api - Replace /objects/one endpoint with /object

- src/pkg/config/persistent_config.go
This line: 
```
if Config.UserToken != "" {
viper.Set(ApiUserTokenKey, Config.UserToken)
return
}
```
was causing the CLI to never load the selected organization ID into the viper context.
> Fix: selected organization ID wasn't loaded to viper context

- .gitattributes
- src/cmd/root.go
- src/cmd/version/apiversion.go
- src/pkg/cloudclient/restapi/client.go
- src/pkg/cloudclient/restapi/cloudapi/api.gen.go
- src/pkg/cloudclient/restapi/cloudapi/openapi.json
- src/pkg/cloudclient/restapi/generate.go
- src/pkg/cloudclient/restapi/version.go
* add `otterize api-version` cmd that reads the openapi specs version from otterize cloud, and prints it to the screen or formats it as a go file in the given path+package
* use `otterize api-version` in codegen process to store the API version along with the compiled API specs
* compare cloud API version and compiled API version when initializing cloud clients and issue a warning in case of mismatch. 
https://www.notion.so/otterize/API-versioning-changes-dfdf7364fff04e69ba70a47919ea306f
> Read cloud API version, store it as part of codegen process, and issue warning if cloud version at runtime is different than it was at compile time

- src/cmd/mapper/export/mapper-export.go
Until this PR when using `mapper export` without providing `--output` flag the user received error.
This happened since the flag `--output-type` was set to default on init and the function identified that type flag was provided without `--output` and printed error
This PR fix it by setting `--output-type` to default  only after checking if the `--output` is set
> Don't show error when --output is omitted

- src/cmd/mapper/mapper-list.go
In https://github.com/otterize/network-mapper/issues/63, undera used the CLI and did not receive output because there was no traffic detected. This change outputs a helpful message in this case, that explains when traffic is detected.
> Print helpful message when no connections found

- src/pkg/cloudclient/restapi/client.go
- src/pkg/cloudclient/restapi/cloudapi/openapi.json
Parse custom error message returned by REST API on HTTP errors, and display it to the caller. 
```
$  otterize users get asdsad                                       
Error: HTTP error 404 (user not found)
exit status 1
```
> Parse and display custom http error message on http errors

- src/cmd/integrations/create/create-kubernetes-integration.go
- src/pkg/cloudclient/restapi/cloudapi/api.gen.go
- src/pkg/cloudclient/restapi/cloudapi/openapi.json
K8s integration name is now auto-generated from the cluster name, so there is no need to provide a name anymore
https://www.notion.so/otterize/Autogenerated-integration-name-should-be-different-3e810219b32a46dba99c57353c0cd366
https://www.notion.so/otterize/Integrations-API-improvements-Kubernetes-integration-name-should-be-the-cluster-name-not-autogener-c31b4739d654423bad0d338aa49b158d
> K8s integration auto-generates name from cluster name

- src/cmd/clusters/update/update-cluster.go
When user sent more than one config flag, the last one override the configuration object. 
This PR fix it to support setting multiple configurations at once.
> Fix multiple cluster config update

- .goreleaser.yaml
Right now the release action fails on go generate.
Our go generate requires running an instance of the SOFA server to work, and because our generated code is committed anyway, it is not required to run go generate on the build.
> Removed go generate from build as it is not required so fix release github action

- src/cmd/intents/convert/convert-intents.go
- src/cmd/intents/intents.go
- src/cmd/networkmapper/mapper.go
This command was moved to the network-mapper command before, but per product request we'll be moving it back to under intents.
> Move intents convert command back to under 'intents'

- src/pkg/cloudclient/enums/enums.go
Because all enums are of string-ish types, it is better to use the `~string` constraint in the types formatting method so that we can use string conversion.
> Using generics better in types formatting function

- src/pkg/portforwarder/portforwarder.go
Before this PR, the portforward kubeclient started by `otterize mapper` commands would sometimes emit errors when the connection was closed upon terminating. These errors were benign, and this logger is not necessary as we would've received the most relevant errors when trying to connect to the port forwarded port, or when starting the port forward.
> Silence errors printed by kubeclient log

- .github/workflows/build.yaml
- .goreleaser.yaml
The last release included `graphviz`, which introduced a dependency on `libc`. We didn't include flags for statically linking with libc, so if the relevant versions are missing, the CLI fails to start.
> Fix static linking with libc

- src/pkg/cloudclient/graphql/generate.go
- src/pkg/cloudclient/graphql/schema.graphql
- src/pkg/cloudclient/restapi/cloudapi/api.gen.go
- src/pkg/cloudclient/restapi/cloudapi/openapi.json
- src/pkg/cloudclient/restapi/generate.go
Use https://app.staging.otterize.com/api as code generation source to guarantee API version consistency (local versioning has some development-only API options which mess up the version hash). 
This also makes the CLI's code generation consistent with all other opensource tools.
> Bump otterize CLI version - use staging as source for version consistency

- .github/workflows/release-tag.yaml
Fix update docs upon release by using ref:main in the checkout git action.
> Fix update docs upon release

- go.mod
- go.sum
- src/cmd/networkmapper/export/mapper-export.go
Until this PR when exporting intents to file, the file contained only service name. In case of multiple services with same name in different namespaces, they would just override each other.
This PR fix add namespace to file name
> Use namespace in exported intent file name

- src/pkg/portforwarder/portforwarder.go
PR fixes the trailing slash which is present at the end of `config.Host` when trying to establish a port-forward. 
Also included some import reordering fixup because yay linters
Fixes Issue #125 
Tested this locally successfully after removing affronting slash.
> portforward - remove trailing slash at the end of config.Host

- src/pkg/intentsoutput/transform.go
Since we had missing kafka operation in mapperKafkaOperationToAPI - "DESCRIBE_CONFIGS",
we've got panic errors.
Added this case to the switch case.
> Fixed a crash when "DESCRIBE_CONFIGS" operation was exported by the mapper export command

- src/cmd/networkmapper/shared/shared.go
- src/pkg/intentsoutput/transform.go
- src/pkg/mapperclient/generated.go
- src/pkg/mapperclient/genqlient.graphql
- src/pkg/mapperclient/schema.graphql
Adds support to export ClientIntents for traffic to Kubernetes services from new versions of the network mapper, specifying the Kubernetes service name, such as:
```yaml
calls:
- name: svc:k8s-service
```
This is an experimental feature and the format for ClientIntents will change to accommodate this new feature.
Adds support for the new Kubernetes service feature in https://github.com/otterize/network-mapper/pull/145
> Add support for exporting destination Kubernetes service

- src/pkg/cloudclient/login/userlogin/userlogin.go
- src/pkg/cloudclient/restapi/client.go
On `otterize login`, the pre-selected org ID should not be sent when querying the current user information from the cloud API. That is because it might be an invalid organization ID, for example if the old organization has been removed, or if the called is switching users. 
The pre-selected org ID will be used only after validating it is, indeed, a valid organization for the logged-in user. 
Reproducing the issue (prior to this fix):
1. Run `otterize login` and complete the login flow
2. Manually edit `~/.otterize/credentials`, set the `organization_id` to some invalid organization
3. Run `otterize login` again
Prior to this fix, the second run of `otterize login` would fail with HTTP error 403 (due to the invalid org). 
After this fix, on the second run of `otterize login`, the CLI will …
> Do not send previous selected organization ID to cloud on `otterize login`

- src/pkg/portforwarder/portforwarder.go
Closes https://github.com/otterize/network-mapper/issues/162.
Prior to this PR, we would manually construct the url.URL object passed to the port forwarder using in connecting to the network mapper in your cluster. With some configurations, this could lead to incorrect URLs. We now use url.Parse and url.Join to construct the URL.
> Fixed bug where port forward URL for mapper CLI could be incorrectly constructed sometimes

- src/cmd/integrations/create/create-database-integration.go
- src/cmd/integrations/create/create-integration.go
- src/pkg/cloudclient/enums/enums.go
- src/pkg/cloudclient/graphql/schema.graphql
- src/pkg/cloudclient/restapi/cloudapi/api.gen.go
- src/pkg/cloudclient/restapi/cloudapi/openapi.json
- src/pkg/output/formatters.go
- src/pkg/telemetry/telemetrygql/schema.graphql
- Add support to the new database integration type.
- New database integration can be created using `integration create` and supplying the details.
- Database address and masked credentials are now added when needed to `integration get` and `integration list`.
> Add support for list/get/create database integrations

- src/cmd/integrations/create/create-github-integration.go
- src/cmd/integrations/create/create-integration.go
Add the create GitHub integration command which prompts the user to add the integration using Otterize Cloud, providing the link.
> Add support for create GitHub integrations

- src/pkg/kafkamapper/mapper.go
- src/pkg/portforwarder/portforwarder.go
Use default kubectl config loading rules. Prior to this PR, the otterize CLI expected to find the config in `~.kube/config`. Now it abides by the same rules as `kubectl`.
> Use default kubectl config loading rules

- src/pkg/intentsoutput/intentslister/lister.go
Until this PR, when printing `otterize mapper list` output the Kafka and HTTP resources would be printed to `stderr` instead of `stdout`, while the intents lines where printed to `stdout`. Since the bugsnag SDK was added, the stderr would be printed in small delay and not synchronously with stdout. This also caused breaks when the user redirect the output of one stream into a file, resulting in only part of the table get printed. This PR use stdout for all the printed lines.
> Fix bug where mapper list command print line in wrong order when intents have HTTP resources

- go.mod
- src/pkg/intentsoutput/transform.go
The service named `kubernets.default` is not always backed by a pod. Therefore we prefer to export it as with a `svc:` prefix - so the output intent will always work.
> Always export communication to the kubernetes API service as `svc:kubernetes.default`

- src/pkg/intentsoutput/intentsvisualizer/visualizer.go
Fix bug where mapper visualize could get the wrong target namespace
> Fix bug where `mapper visualize` could use the wrong target namespace

- src/cmd/clientintents/export/export-clientintents.go
- src/cmd/clientintents/export/utils.go
- src/pkg/cloudclient/graphql/schema.graphql
- src/pkg/cloudclient/restapi/cloudapi/api.gen.go
- src/pkg/cloudclient/restapi/cloudapi/openapi.json
- src/pkg/mapperclient/schema.graphql
- src/pkg/output/formatters.go
Enhance support for exporting ClientIntents from otterize cloud, using `otterize clientintents export` cmd. 
The new command supports filtering by:
- Cluster(s)
- Namespace(s)
- Service(s)
It also supports outputting the resulting ClientIntents to file or directory, similar to the `otterize network-mapper export` command. 
See `otterize clientintents export --help` for more details. 
Filtering by clusters, namespaces or services currently supports specifying object ids only. Support for filtering by object names will be added in a future PR. 
Usage example:
```shell
$ otterize clientintents export --clusters cluster_zhxht8rwej -o /tmp/clientintents --output-type dir
Successfully wrote intents into /tmp/clientintents
```
Additionally, exported ClientIntent files now contain comments …
> Support otterize clientintents export from cloud by clusters, namespaces & service filters

- src/cmd/clientintents/export/export-clientintents.go
- src/pkg/cloudclient/graphql/schema.graphql
- src/pkg/cloudclient/restapi/cloudapi/api.gen.go
- src/pkg/cloudclient/restapi/cloudapi/openapi.json
- src/pkg/cloudclient/restapi/generate.go
This PR adds support for exporting ClientIntents for both version v1 & v2, by passing the `--output-version / -v` flag to `otterize clientintents export`. 
See `otterize clientintents export --help` for more details.
> Support exporting ClientIntents in version v2 in 'otterize clientintents export' command

- src/cmd/clientintents/export/export-clientintents.go
- src/cmd/clientintents/export/utils.go
- src/pkg/output/formatters.go
This PR adds support for enabling/disabling applied-discovered diff comments in `otterize clientintents export` cli command, using the `--diff` flag (default to false).
> Support enabling/disabling diff comments in otterize clientintents export

- src/cmd/clientintents/export/utils.go
- src/pkg/cloudclient/graphql/schema.graphql
- src/pkg/cloudclient/restapi/cloudapi/api.gen.go
- src/pkg/cloudclient/restapi/cloudapi/openapi.json
- src/pkg/output/formatters.go
This PR modifies the output format of `otterize clientintents export` when used with `--output-type dir`. The generated output files will now include the namespace name (`client.mynamespace.yaml` rather than just `client.yaml`), to prevent conflicts on workloads with similar names in different namespaces.
> Include namespace name in generated filenames on otterize clientintents export to dir

- src/pkg/cloudclient/graphql/schema.graphql
- src/pkg/cloudclient/login/userlogin/userlogin.go
- src/pkg/cloudclient/restapi/cloudapi/api.gen.go
- src/pkg/cloudclient/restapi/cloudapi/openapi.json
- src/pkg/mapperclient/schema.graphql
This PR fixes an issue where otterize-cli would fail on login for users belonging to more than one organization, with the following error: 
```
Error: user belongs to multiple organizations, but no organization was specified using the X-Otterize-Organization header (HTTP error 400)
```
> Fix an issue where otterize-cli login would fail on users belonging to multiple organizations

- src/pkg/cloudclient/restapi/client.go
This PR adds support for debug logging of HTTP requests & their duration, by utilizing the `OTTERIZE_DEBUG` environment variable. 
Usage: 
```
> OTTERIZE_DEBUG=true otterize namespaces list
...
time="2025-04-21T23:08:29+03:00" level=debug msg="HTTP request" method=GET url="http://app.otterize.com/api/rest/v1beta/namespaces"
time="2025-04-21T23:08:56+03:00" level=debug msg="HTTP request done" duration=26.921086583s method=GET url="http://app.otterize.com/api/rest/v1beta/namespaces"
...
```
> Add support for debug logging of HTTP API requests & their duration, by utilizing the OTTERIZE_DEBUD environment variable. 
